# Extra autostart processes
# exec-once = uwsm-app -- my-service
# exec-once = uwsm-app -- swaybg -i ~/.wallpaper1.png -m fill >/dev/null 2>&1 &
exec-once = killall swaybg
exec-once = hyprpaper >/dev/null 2>&1 &
exec-once = ibus-daemon -drx --panel disable
env = GTK_IM_MODULE,wayland
env = QT_IM_MODULE,wayland;ibus
