# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
env = GDK_SCALE,1
monitor=DP-1,preferred,auto,auto
monitor=DP-2,preferred,-1920x60,auto # LAPTOP: comment this
