# Hyprland monitor configuration
env = GDK_SCALE,1

# Desktop monitors (rain)
monitor=DP-1,1920x1080@165,1920x-80,1
monitor=DP-2,preferred,0x0,1

# Laptop / fallback display (sky)
monitor=,preferred,auto,auto
